spring:
  application:
    name: heatstone-api
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driverClass: com.mysql.jdbc.Driver
    password: test
    url: "jdbc:mysql://116.62.114.108/heat-stone-party"
    username: test
freemarker: 
  cache: false
  charset: UTF-8
  check-template-location: true
  content-type: text/html
  expose-request-attributes: true
  expose-session-attributes: true
  request-context-attribute: request
multipart: 
  maxFileSize: 50Mb
  maxRequestSize: 500Mb
mybatis: 
  mapperLocations: "classpath:mapper/*.xml"
  typeAliasesPackage: com.blizzard.heatstone.api.dao
server: 
  port: 8081
com:
  qiniu:
    storage:
      accessKey: YPjo-AehHWZnR-xvCuY7hS-5vQ6AwO40Th2D76Co
      secretKey: 4yB_PeHEcMLsfEoC6iwxYoQn0WMbC8atHrUnsrXr
      domain: "http://oslkcublz.bkt.clouddn.com/"
      bucketName: heat-stone

